palette             = "primary"

format              = "$directory $git_branch :: "

[time]
disabled            = false
time_format         = "%R"
style               = "blue"

[directory]
style               = "blue"
format              = "[$path]($style)"
truncation_length   = 2
truncation_symbol   = " -"

[git_branch]
style               = "pink"
format              = "[$branch(:$remote_branch)]($style)"
truncation_length   = 24
truncation_symbol   = "…"

[palettes.primary]
blue = "#98BED3"
pink = "#CCCCCC" # "#FF0088"
