github.com:
    user: IngmarFalk
    oauth_token: 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
    git_protocol: https
    users:
        IngmarFalk:
            oauth_token: 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
